title: My name is zzzzzczcnnnn
description: (V002-20201217).
      This site is managed by VauLSMorg (vlsm.org) since 2020.
      <br>May the fork() be with you, Jolan Tru!
google_analytics: UA-89852122-6
disc: You are free to share, copy and redistribute the material of this site 
      in any medium or format for any purpose, even commercially. 
      Please give appropriate credit, provide a link to the page, 
      and indicate if changes were made. You may do so in any reasonable manner. 
      You should not apply legal terms or technological measures, 
      that legally restrict others from doing anything that is permited here.
author: zzzzzczcnnnn
show_downloads: false
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: URLs
  links:
    - https://https://github.com/zzzzzczcnnnn/os202/
# github:
#    zip_url: https://github.com/...
#    tar_url: https://github.com/...
github: [metadata]


